### ISSUE TITLE
Got it to work?

### ISSUE THREAD

**Issue by rvalle** [cobraz/eaccounting#1]
Hi!

I am not sure if this does work or not. Docs mention that it is in early stage, but is it functional?

How do you authorize the client application?

**Comment by simenandre** [comment]
Hello,

It is definitely not production ready. I've made a convenient way of authorizing for server-only communication. How are you planning on using it? I might be able to help out!

**Comment by rvalle** [comment]
We want our customers to see if they have open invoices with us. It is pretty much an in-house development.

OAuth is a bit of a pain asking for interactive authentication in this particular case.

I see you seem to rely on refresing an access token, but I am not sure where the token is created for the first time, where the application is authorized.

**Comment by BagheeraBear** [comment]
I would have the same question: I am not sure where the token is created for the first time, where the application is authorized?

**Comment by simenandre** [comment]
It's not currently developed. I will accept pull requests. 👍

**Comment by rvalle** [comment]
@BagheeraBear you create the token once (interactively) and then you can refresh it whenever it has expired.

In practice, what we are doing is that our application will log an URL if an interactive authorization is required. After authorizing once, you don't need to do it any more. In fact we save tokens to a file and we can even upgrade new releases of our app without having to authorize again. You need to create a token listener (HTTP endpoint) where Visma will redirect the browser after interactive auth is successful, that is how you receive the token. Then you only refresh it.

We have had our self service billing portal running since september'17 with no issues at all. 

during the process we actually decided to use OAuth directly, without this library. The question is that once you implement this auth system, the rest is pretty straight forward. 

However we are happy to share our code.

Here are some tests I wrote to understand the authorization process.

https://pastebin.com/K6sctAnD

Here are some tests for refreshing the token:

https://pastebin.com/TjKiuPW4

**Comment by BagheeraBear** [comment]
@rvalle Thank you! I am really grateful for all help I can get. I see also the rest as pretty straightforward as soon as I can get the authentication to work.

**Comment by BagheeraBear** [comment]
@rvalle Hi again! Do you think you could share what it looks like in the actual call to get the access token? I have the authorization code already (to a https-page). best regards! Uffe

**Comment by rvalle** [comment]
@BagheeraBear the token you get via the HTTP callback. 

I wrote something that I called the token listener to receive it.

Remember, You have to contact visma support, and request that they set up those URLs both for development and production. I kind of remember that the standard setup for development was OK, like localhost:3000 or something similar. You can just test and see where your browser redirects to after autorizing.

I can share the token listener that I have:

https://pastebin.com/tSkK96fS

Maybe you find this class useful also, it is the eAccounting module I use.

https://pastebin.com/RYZpPmY8

**Comment by BagheeraBear** [comment]
@rvalle Thank you very much! Visma are using localhost and https, so I'll give this a go! Again, thanks a lot

**Comment by rvalle** [comment]
You are welcome! if you manage to download PDFs for invoices let me know... that I still have to look into...

**Comment by simenandre** [comment]
I'm gonna call this stale :)

Heads up, there are large changes being made to this library. #9
